//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingTravelsExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carriers
    {
        public int carr_Id { get; set; }
        public string carr_FirstName { get; set; }
        public string carr_LastName { get; set; }
        public string carr_Address { get; set; }
        public string carr_Tel { get; set; }
        public string remarks { get; set; }
    }
}
