//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikingTravelsExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int cust_Id { get; set; }
        public string cust_FirstName { get; set; }
        public string cust_LastName { get; set; }
        public string cust_Address { get; set; }
        public string cust_Tel { get; set; }
    }
}
